"""empty message

Revision ID: d1782b713b25
Revises: 9eeba46b74de
Create Date: 2024-11-13 14:44:11.436503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1782b713b25'
down_revision = '9eeba46b74de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danselektion', schema=None) as batch_op:
        batch_op.alter_column('dato',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('elev', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fornavn', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('efternavn', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mobil', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lokation_id')
        batch_op.drop_column('navn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elev', schema=None) as batch_op:
        batch_op.add_column(sa.Column('navn', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('lokation_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'lokation', ['lokation_id'], ['id'])
        batch_op.drop_column('mobil')
        batch_op.drop_column('efternavn')
        batch_op.drop_column('fornavn')

    with op.batch_alter_table('danselektion', schema=None) as batch_op:
        batch_op.alter_column('dato',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
